version: '3.8'

services:
  mysql:
    build: ./sql
    image: image_sql
    container_name: mysql_container
    hostname: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${MYSQL_PORT}:${MYSQL_CONTAINER_PORT}"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - aibt_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    container_name: frontend_dev
    build: ./frontend
    ports:
      - "${FRONT_CONTAINER_PORT}:${FRONT_CONTAINER_PORT}"
    volumes:
      - ./frontend:/var/www/frontend
    env_file: .env
    environment:
      - NODE_ENV=development
    networks:
      - aibt_network

  backend:
    container_name: backend_dev
    build: ./backend
    ports:
      - "${BACKEND_CONTAINER_PORT}:${BACKEND_CONTAINER_PORT}"
    command: uwsgi --ini /var/www/backend/uwsgi.ini
    volumes:
      - ./backend:/var/www/backend
      - /var/run/docker.sock:/var/run/docker.sock
      - socket:/tmp
    tty: true
    depends_on:
      - mysql
    env_file: .env
    networks:
      - aibt_network

  nginx:
    image: nginx:1.24
    container_name: aibt_nginx-dev
    env_file: .env
    networks:
      - aibt_network
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx:/etc/nginx/templates
      - ./backend:/var/www/backend
      - ./ai_server:/var/www/ai_server
      - ./nginx/log:/var/log/nginx
      - ./nginx/html:/usr/share/nginx/html
      - socket:/tmp
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    depends_on:
      - translation_1
      - translation_2
      - translation_3
      - frontend
    tty: true

  db_to_queue:
    build: ./db_to_queue
    image: image_db_to_queue
    container_name: db_to_queue_containers
    depends_on:
      mysql:
        condition: service_healthy
      translation_1:
        condition: service_started
      translation_2:
        condition: service_started
      translation_3:
        condition: service_started
    env_file: .env
    ports:
      - "${db_to_queue_CONTAINER_PORT}:${db_to_queue_CONTAINER_PORT}"
    networks:
      - aibt_network

  translation_1:
    build: ./ai_server
    image: translation
    container_name: translation_1
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "5002:5004"
    volumes:
      - ./ai_server:/var/www/ai_server
      - ./backend/input_audio_files:/mnt/input_audio_files
      - /mnt/d/Transcription/Systranfaster_whisper_large_v2:/app/models/faster_whisper_large_v2
    tty: true
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    env_file: .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia
    networks:
      - aibt_network

  translation_2:
    build: ./ai_server
    image: translation
    container_name: translation_2
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "5003:5004"
    volumes:
      - ./ai_server:/var/www/ai_server
      - ./backend/input_audio_files:/mnt/input_audio_files
      - /mnt/d/Transcription/Systranfaster_whisper_large_v2:/app/models/faster_whisper_large_v2
    tty: true
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    env_file: .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia
    networks:
      - aibt_network

  translation_3:
    build: ./ai_server
    image: translation
    container_name: translation_3
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "5004:5004"
    volumes:
      - ./ai_server:/var/www/ai_server
      - ./backend/input_audio_files:/mnt/input_audio_files
      - /mnt/d/Transcription/Systranfaster_whisper_large_v2:/app/models/faster_whisper_large_v2
    tty: true
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    env_file: .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia
    networks:
      - aibt_network

networks:
  aibt_network:
    external: true

volumes:
  socket:
    name: socket_volume
